import { Structure } from '../models';

export const structures: Structure[] = [
  {
    id: 'burj-khalifa',
    name: 'Burj Khalifa',
    category: 'Skyscraper',
    location: 'Dubai, UAE',
    city: 'Dubai',
    country: 'UAE',
    height: 828,
    floors: 163,
    year: 2010,
    latitude: 25.1972,
    longitude: 55.2744,
    description:
      'The Burj Khalifa is the tallest building in the world and a global icon of modern engineering. Designed by Skidmore, Owings & Merrill, it rises 828 meters above downtown Dubai. The tower features more than 160 habitable floors, luxury residences, corporate suites, the Armani Hotel and a public observation deck on floors 124, 125 and 148. Its unique buttressed core structure, inspired by the desert flower Hymenocallis, helps the building withstand strong winds while creating unmatched panoramic views. On clear days visitors can see up to 95 kilometers from the top.',
    image: require('../../assets/burjKhalifa.png'),
  },
  {
    id: 'shanghai-tower',
    name: 'Shanghai Tower',
    category: 'Skyscraper',
    location: 'Shanghai, China',
    city: 'Shanghai',
    country: 'China',
    height: 632,
    floors: 128,
    year: 2015,
    latitude: 31.2336,
    longitude: 121.5055,
    description:
      'Shanghai Tower is a twisting, 632-meter supertall skyscraper in the heart of Lujiazui financial district. Its distinctive 120-degree twist reduces wind loads on the structure by nearly a quarter, saving thousands of tons of steel. The double-skin glass facade creates nine atrium sky gardens that function as vertical parks. The building is home to offices, a luxury hotel, retail, and one of the world’s highest observation decks on floor 121. Some of the fastest elevators ever built travel inside at over 20 meters per second.',
    image: require('../../assets/shanghaiTower.png'),
  },
  {
    id: 'abraj-al-bait',
    name: 'Abraj Al Bait Clock Tower',
    category: 'Skyscraper',
    location: 'Mecca, Saudi Arabia',
    city: 'Mecca',
    country: 'Saudi Arabia',
    height: 601,
    floors: 120,
    year: 2012,
    latitude: 21.4181,
    longitude: 39.8257,
    description:
      'Abraj Al Bait, also known as the Makkah Royal Clock Tower, is a landmark complex standing right next to the Great Mosque of Mecca. The central tower features the largest clock face in the world, visible from over 25 kilometers away. The complex houses hotels, residences, prayer halls and shopping galleries that serve millions of pilgrims each year during Hajj. Its illuminated crescent and clock lighting create a dramatic nightly display over the holy city.',
    image: require('../../assets/abrajAlBaitClockTower.png'),
  },
  {
    id: 'ping-an',
    name: 'Ping An Finance Center',
    category: 'Skyscraper',
    location: 'Shenzhen, China',
    city: 'Shenzhen',
    country: 'China',
    height: 599,
    floors: 115,
    year: 2017,
    latitude: 22.533,
    longitude: 114.0555,
    description:
      'The Ping An Finance Center is a sleek 599-meter skyscraper that represents Shenzhen’s rapid rise as a global tech and finance hub. Its tapered crown and stainless-steel cladding were engineered to resist corrosion and typhoon-force winds common in southern China. The building includes offices, a luxury hotel, shopping, and an observation deck called Free Sky on floors 115–116. Advanced damping systems allow the tower to remain stable even during strong seismic events.',
    image: require('../../assets/pingAnFinanceCenter.png'),
  },
  {
    id: 'lotte-world',
    name: 'Lotte World Tower',
    category: 'Skyscraper',
    location: 'Seoul, South Korea',
    city: 'Seoul',
    country: 'South Korea',
    height: 555,
    floors: 123,
    year: 2016,
    latitude: 37.5131,
    longitude: 127.1025,
    description:
      'Lotte World Tower is the tallest building in South Korea at 555 meters with 123 floors. Its elegant tapered form is inspired by traditional Korean ceramics and calligraphy brushes. The tower contains offices, luxury residences, a six-star hotel, premium retail and the Seoul Sky observation deck with glass-floor platforms. Engineered for high seismic activity and strong winds, the structure uses deep bedrock foundations reaching 38 meters underground. Visitors often come for the panoramic views over the Han River and the Seoul skyline.',
    image: require('../../assets/lotteWorldTower.png'),
  },
  {
    id: 'one-wtc',
    name: 'One World Trade Center',
    category: 'Skyscraper',
    location: 'New York, USA',
    city: 'New York',
    country: 'USA',
    height: 541,
    floors: 104,
    year: 2014,
    latitude: 40.7127,
    longitude: -74.0134,
    description:
      'One World Trade Center, also known as the Freedom Tower, is the centerpiece of the rebuilt World Trade Center complex in Lower Manhattan. Its symbolic height of 1,776 feet references the year of American independence. The building includes offices, broadcast facilities and the One World Observatory on floors 100–102, which offers sweeping views of Manhattan, Brooklyn and the Statue of Liberty. The structure combines a reinforced concrete core with high-performance glass, designed with lessons learned from the original towers to achieve industry-leading safety standards.',
    image: require('../../assets/oneWorldTradeCenter.png'),
  },
  {
    id: 'guangzhou-ctf',
    name: 'Guangzhou CTF Finance Centre',
    category: 'Skyscraper',
    location: 'Guangzhou, China',
    city: 'Guangzhou',
    country: 'China',
    height: 530,
    floors: 111,
    year: 2016,
    latitude: 23.117,
    longitude: 113.3246,
    description:
      'Guangzhou CTF Finance Centre is a 530-meter mixed-use skyscraper in the Zhujiang New Town district. It houses offices, luxury apartments, a Rosewood Hotel and shopping space. Its four stepped setbacks reduce wind turbulence while maximizing views across the Pearl River. The tower is famous for its ultra-fast elevators, which were among the first to reach speeds over 20 meters per second. A sky lobby on the 108th floor provides dramatic vistas of the Canton Tower and the river below.',
    image: require('../../assets/guangzhouCtfFinanceCentre.png'),
  },
  {
    id: 'tianjin-ctf',
    name: 'Tianjin CTF Finance Centre',
    category: 'Skyscraper',
    location: 'Tianjin, China',
    city: 'Tianjin',
    country: 'China',
    height: 530,
    floors: 98,
    year: 2019,
    latitude: 39.0842,
    longitude: 117.201,
    description:
      'Tianjin CTF Finance Centre rises 530 meters in the Binhai district and is recognized for its aerodynamic softly curving form. The design reduces wind vortices and helps the tower remain stable in coastal storms. It contains premium offices, serviced apartments, a five-star hotel and observation facilities near the top. The building’s crystalline glass facade reflects the sky by day and glows with integrated LED lighting at night, turning it into a beacon of modern Tianjin.',
    image: require('../../assets/tianjinCtfFinanceCentre.png'),
  },
  {
    id: 'citic-tower',
    name: 'CITIC Tower',
    category: 'Skyscraper',
    location: 'Beijing, China',
    city: 'Beijing',
    country: 'China',
    height: 528,
    floors: 109,
    year: 2018,
    latitude: 39.9042,
    longitude: 116.4074,
    description:
      'CITIC Tower, also called China Zun, is the tallest building in Beijing at 528 meters. Its silhouette was inspired by the zun, an ancient Chinese ceremonial wine vessel, giving the tower a gently flared top and base with a slender waist. Situated in the Central Business District, it houses the global headquarters of CITIC Group, offices, conference centers and premium amenities. Engineers designed it to withstand earthquakes up to magnitude 8, using a dual system of steel megacolumns and reinforced cores.',
    image: require('../../assets/citicTower.png'),
  },
  {
    id: 'taipei-101',
    name: 'Taipei 101',
    category: 'Skyscraper',
    location: 'Taipei, Taiwan',
    city: 'Taipei',
    country: 'Taiwan',
    height: 508,
    floors: 101,
    year: 2004,
    latitude: 25.0339,
    longitude: 121.5645,
    description:
      'Taipei 101 is a 508-meter landmark of Taiwan and was the tallest building in the world from 2004 to 2010. Its eight stacked sections are a nod to traditional Chinese pagodas and symbolize prosperity. A massive 660-ton tuned mass damper, one of the largest ever built, is suspended between the 87th and 92nd floors to counteract typhoons and earthquakes. The tower contains offices, luxury retail, restaurants and a public observatory with views of Taipei’s mountains and coastline.',
    image: require('../../assets/taipei101.png'),
  },
  {
    id: 'tokyo-skytree',
    name: 'Tokyo Skytree',
    category: 'Tower',
    location: 'Tokyo, Japan',
    city: 'Tokyo',
    country: 'Japan',
    height: 634,
    year: 2012,
    latitude: 35.71,
    longitude: 139.8107,
    description:
      'Tokyo Skytree is the tallest tower in the world and the second-tallest freestanding structure. Standing 634 meters tall, its height references the ancient name of the Tokyo region, Musashi. It provides digital television and radio broadcasting for the capital region while also welcoming millions of visitors to its Tembo Deck (350 m) and Tembo Galleria (450 m). Engineered for earthquake resistance using a central shinbashira column inspired by traditional Japanese pagodas, it remains steady even during strong seismic events.',
    image: require('../../assets/tokyoSkytree.png'),
  },
  {
    id: 'canton-tower',
    name: 'Canton Tower',
    category: 'Tower',
    location: 'Guangzhou, China',
    city: 'Guangzhou',
    country: 'China',
    height: 604,
    year: 2010,
    latitude: 23.1085,
    longitude: 113.319,
    description:
      'Canton Tower is a 604-meter observation and broadcast tower with an unmistakable hourglass silhouette. Its twisted hyperboloid lattice structure was engineered to handle high winds and typhoons. Visitors can ride glass-floor elevators to observation decks, dine in rotating restaurants, or experience the Sky Drop, one of the world’s highest thrill rides. At night the tower lights up in shifting colors, making it a signature feature of the Pearl River skyline.',
    image: require('../../assets/cantonTower.png'),
  },
  {
    id: 'cn-tower',
    name: 'CN Tower',
    category: 'Tower',
    location: 'Toronto, Canada',
    city: 'Toronto',
    country: 'Canada',
    height: 553,
    year: 1976,
    latitude: 43.6426,
    longitude: -79.3871,
    description:
      'The CN Tower is a 553-meter concrete communications and observation tower in the heart of Toronto. For 32 years it held the record as the tallest freestanding structure on Earth. Its main attractions include the Glass Floor and LookOut at 346 meters, the SkyPod at 447 meters, and the adrenaline-fueled EdgeWalk around the outside of the pod. 360 Restaurant rotates fully once every 72 minutes, offering a constantly changing skyline view over Lake Ontario.',
    image: require('../../assets/cnTower.png'),
  },
  {
    id: 'ostankino-tower',
    name: 'Ostankino Tower',
    category: 'Tower',
    location: 'Moscow, Russia',
    city: 'Moscow',
    country: 'Russia',
    height: 540,
    year: 1967,
    latitude: 55.8198,
    longitude: 37.6116,
    description:
      'Ostankino Tower in Moscow is a historic broadcasting and observation tower completed in 1967. Its 540-meter concrete shaft was revolutionary at the time and made it the tallest freestanding structure in the world for nine years. The tower hosts observation decks, a panoramic restaurant and major Russian TV transmission equipment. Its prestressed concrete design has been studied by engineers worldwide as a benchmark for high-rise tower construction.',
    image: require('../../assets/ostankinoTower.png'),
  },
  {
    id: 'milad-tower',
    name: 'Milad Tower',
    category: 'Tower',
    location: 'Tehran, Iran',
    city: 'Tehran',
    country: 'Iran',
    height: 435,
    year: 2007,
    latitude: 35.7447,
    longitude: 51.3756,
    description:
      'Milad Tower is the tallest structure in Iran and one of the tallest telecommunications towers in the world at 435 meters. Its twelve-story head includes restaurants, art galleries, a convention center and an open-air observation deck. The octagonal concrete shaft represents classical Iranian geometry while the sleek crown was designed to blend tradition with modernity. The tower sits on a hilltop, which extends its visibility across most of Tehran.',
    image: require('../../assets/miladTower.png'),
  },
  {
    id: 'kl-tower',
    name: 'KL Tower',
    category: 'Tower',
    location: 'Kuala Lumpur, Malaysia',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    height: 421,
    year: 1995,
    latitude: 3.1528,
    longitude: 101.7037,
    description:
      'Menara Kuala Lumpur, better known as KL Tower, is a 421-meter communications tower nestled within a protected forest reserve. Visitors can take express elevators to the Sky Deck, Sky Box and observation levels for 360-degree views of the city and the Petronas Twin Towers. Cultural performances, a revolving restaurant and adventure activities such as BASE jumping events make it a popular destination. Its unique location inside a rainforest makes it one of the greenest urban towers in the world.',
    image: require('../../assets/klTower.png'),
  },
  {
    id: 'tashkent-tower',
    name: 'Tashkent Tower',
    category: 'Tower',
    location: 'Tashkent, Uzbekistan',
    city: 'Tashkent',
    country: 'Uzbekistan',
    height: 375,
    year: 1985,
    latitude: 41.3385,
    longitude: 69.3344,
    description:
      'Tashkent Tower is a 375-meter Soviet-era broadcasting tower and one of the tallest structures in Central Asia. Its unique geometric silhouette features a ring-shaped observation platform and a rotating restaurant halfway up the shaft. Designed to withstand the strong seismic activity of the region, the tower remains a key landmark and favorite observation point for visitors exploring the Uzbek capital.',
    image: require('../../assets/tashkentTower.png'),
  },
  {
    id: 'sky-tower',
    name: 'Sky Tower',
    category: 'Tower',
    location: 'Auckland, New Zealand',
    city: 'Auckland',
    country: 'New Zealand',
    height: 328,
    year: 1997,
    latitude: -36.8485,
    longitude: 174.7633,
    description:
      'Sky Tower is Auckland’s 328-meter telecommunications and observation tower, the tallest freestanding structure in the Southern Hemisphere. It offers observation decks, a revolving restaurant and the famous SkyJump and SkyWalk adventure activities. On clear days visitors can see more than 80 kilometers across the Hauraki Gulf. The tower was engineered to sway safely in strong winds and withstand earthquakes up to magnitude 8.',
    image: require('../../assets/skyTowerAuckland.png'),
  },
  {
    id: 'sydney-tower',
    name: 'Sydney Tower',
    category: 'Tower',
    location: 'Sydney, Australia',
    city: 'Sydney',
    country: 'Australia',
    height: 309,
    year: 1981,
    latitude: -33.8705,
    longitude: 151.2089,
    description:
      'Sydney Tower, also called Sydney Tower Eye, is a 309-meter observation tower above the city’s retail core. Its golden turret houses observation levels, revolving restaurants and the Skywalk outdoor platform. The tower uses 56 high-tension steel cables to secure it against strong winds and was designed to flex in cyclonic conditions. Its 360-degree views cover the Blue Mountains, Sydney Harbour and the Pacific coastline.',
    image: require('../../assets/sydneyTower.png'),
  },
  {
    id: 'oriental-pearl',
    name: 'Oriental Pearl Tower',
    category: 'Tower',
    location: 'Shanghai, China',
    city: 'Shanghai',
    country: 'China',
    height: 468,
    year: 1994,
    latitude: 31.2397,
    longitude: 121.4998,
    description:
      'Oriental Pearl Tower is a 468-meter TV and observation tower on the Huangpu River bank in Shanghai. Its three large spherical structures inspired by pearls on a jade plate became a symbol of the city’s modern rebirth in the 1990s. Visitors enjoy observation decks, a history museum dedicated to Shanghai, and a revolving restaurant. At night it becomes a major feature of the Bund’s illuminated skyline, reflecting across the river alongside nearby skyscrapers.',
    image: require('../../assets/orientalPearlTower.png'),
  },
  {
    id: 'eiffel-tower',
    name: 'Eiffel Tower',
    category: 'Monument',
    location: 'Paris, France',
    city: 'Paris',
    country: 'France',
    height: 330,
    floors: 3,
    year: 1889,
    latitude: 48.8584,
    longitude: 2.2945,
    description:
      'The Eiffel Tower is a 330-meter wrought-iron lattice tower on the Champ de Mars in Paris. Built by Gustave Eiffel’s company for the 1889 Exposition Universelle, it was originally intended to stand for only 20 years. Its revolutionary engineering quickly made it the tallest man-made structure on Earth and a global icon of France. Visitors can ascend to three levels, including a glass-floor section on the first floor and a summit deck with panoramic views of Paris. Over seven million people visit the tower every year.',
    image: require('../../assets/eiffelTower.png'),
  },
  {
    id: 'washington-monument',
    name: 'Washington Monument',
    category: 'Monument',
    location: 'Washington D.C., USA',
    city: 'Washington D.C.',
    country: 'USA',
    height: 169,
    year: 1884,
    latitude: 38.8895,
    longitude: -77.0353,
    description:
      'The Washington Monument is a 169-meter marble obelisk on the National Mall honoring George Washington, the first U.S. president. When completed in 1884 it was the tallest structure in the world. A distinct color change about a third of the way up marks a pause in construction caused by funding issues during the Civil War. The interior elevator carries visitors to an observation room near the top, offering views of the Capitol, Lincoln Memorial and the Potomac River.',
    image: require('../../assets/washingtonMonument.png'),
  },
  {
    id: 'statue-of-liberty',
    name: 'Statue of Liberty',
    category: 'Monument',
    location: 'New York, USA',
    city: 'New York',
    country: 'USA',
    height: 93,
    year: 1886,
    latitude: 40.6892,
    longitude: -74.0445,
    description:
      'The Statue of Liberty is a 93-meter neoclassical copper monument on Liberty Island in New York Harbor. It was a gift from France to the United States in 1886 to celebrate the centennial of American independence and the friendship between the nations. Designed by Frédéric Auguste Bartholdi with an internal framework by Gustave Eiffel, the statue has become a universal symbol of freedom. Visitors can tour the pedestal and, with reservations, climb to the crown for sweeping views of Manhattan and the harbor.',
    image: require('../../assets/statueOfLiberty.png'),
  },
  {
    id: 'gateway-arch',
    name: 'Gateway Arch',
    category: 'Monument',
    location: 'St. Louis, USA',
    city: 'St. Louis',
    country: 'USA',
    height: 192,
    year: 1965,
    latitude: 38.6247,
    longitude: -90.1848,
    description:
      'The Gateway Arch is a 192-meter stainless-steel monument on the banks of the Mississippi River in St. Louis. Designed by architect Eero Saarinen, its flawless catenary curve makes it the tallest arch in the world. Completed in 1965, it commemorates the westward expansion of the United States. A unique tram system inside carries visitors to an observation level at the top, where the floor-to-ceiling windows reveal views of the river and the downtown skyline.',
    image: require('../../assets/gatewayArch.png'),
  },
  {
    id: 'christ-the-redeemer',
    name: 'Christ the Redeemer',
    category: 'Monument',
    location: 'Rio de Janeiro, Brazil',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    height: 38,
    year: 1931,
    latitude: -22.9519,
    longitude: -43.2105,
    description:
      'Christ the Redeemer is a 38-meter Art Deco statue of Jesus Christ standing atop Mount Corcovado at 710 meters above sea level. Completed in 1931, it overlooks the entire city of Rio de Janeiro with arms outstretched in a symbol of peace. Designed by Brazilian engineer Heitor da Silva Costa and French sculptor Paul Landowski, it was named one of the New Seven Wonders of the World in 2007. Visitors reach the statue by a historic cog railway through the Tijuca National Park.',
    image: require('../../assets/christTheRedeemer.png'),
  },
  {
    id: 'motherland-monument',
    name: 'Motherland Monument',
    category: 'Monument',
    location: 'Kyiv, Ukraine',
    city: 'Kyiv',
    country: 'Ukraine',
    height: 102,
    year: 1981,
    latitude: 50.4266,
    longitude: 30.563,
    description:
      'The Motherland Monument is a 102-meter stainless-steel statue overlooking the Dnipro River in Kyiv. Part of the National Museum of the History of Ukraine, the sculpture represents a powerful female figure holding a sword and shield. Completed in 1981, it is one of the tallest statues in Europe and a landmark of the capital’s skyline. Visitors can access two observation platforms inside and learn about the turbulent history of the region at the surrounding memorial complex.',
    image: require('../../assets/motherlandMonument.png'),
  },
  {
    id: 'san-jacinto',
    name: 'San Jacinto Monument',
    category: 'Monument',
    location: 'Texas, USA',
    city: 'La Porte',
    country: 'USA',
    height: 174,
    year: 1939,
    latitude: 29.752,
    longitude: -95.081,
    description:
      'The San Jacinto Monument is a 174-meter limestone column near Houston, Texas, marking the site of the 1836 Battle of San Jacinto that secured Texan independence from Mexico. It is the tallest masonry column monument in the world. Topped by a 34-meter star representing the Lone Star of Texas, it houses the San Jacinto Museum of History at its base and an observation floor offering panoramic views over the battlefield and Buffalo Bayou.',
    image: require('../../assets/sanJacintoMonument.png'),
  },
  {
    id: 'monumento-revolucion',
    name: 'Monumento a la Revolución',
    category: 'Monument',
    location: 'Mexico City, Mexico',
    city: 'Mexico City',
    country: 'Mexico',
    height: 67,
    year: 1938,
    latitude: 19.4363,
    longitude: -99.1549,
    description:
      'The Monumento a la Revolución is a 67-meter triumphal arch dedicated to the Mexican Revolution of 1910. Located in Plaza de la República in Mexico City, it combines Art Deco styling with Mexican socialist realism. The monument is also a mausoleum holding the remains of several key revolutionary figures. A glass elevator installed in 2010 now takes visitors up to the cupola and an outdoor observation mirador with striking views of the capital.',
    image: require('../../assets/monumentoALaRevolucion.png'),
  },
  {
    id: 'bunker-hill',
    name: 'Bunker Hill Monument',
    category: 'Monument',
    location: 'Boston, USA',
    city: 'Boston',
    country: 'USA',
    height: 67,
    year: 1843,
    latitude: 42.3763,
    longitude: -71.0603,
    description:
      'The Bunker Hill Monument is a 67-meter granite obelisk on Breed’s Hill in Charlestown, Boston. It commemorates the 1775 Battle of Bunker Hill, one of the earliest major engagements of the American Revolutionary War. Completed in 1843, it is among the oldest monuments in the United States. Visitors can climb 294 stone steps to a small observation chamber near the top for views of the harbor and the historic neighborhood below.',
    image: require('../../assets/bunkerHillMonument.png'),
  },
  {
    id: 'discoveries',
    name: 'Monument to the Discoveries',
    category: 'Monument',
    location: 'Lisbon, Portugal',
    city: 'Lisbon',
    country: 'Portugal',
    height: 56,
    year: 1960,
    latitude: 38.6936,
    longitude: -9.205,
    description:
      'The Monument to the Discoveries, or Padrão dos Descobrimentos, is a 56-meter limestone monument on the north bank of the Tagus River in Lisbon. It was built in 1960 to commemorate the 500th anniversary of the death of Infante Dom Henrique, known as Henry the Navigator, whose patronage launched the Portuguese Age of Discoveries. The ship-shaped structure features statues of 33 prominent explorers and navigators. An internal elevator and staircase lead to a rooftop terrace offering wide views of the river and Belém district.',
    image: require('../../assets/monumentToTheDiscoveries.png'),
  },
];

export const structureCategories: Array<'All' | 'Skyscraper' | 'Tower' | 'Monument'> = [
  'All',
  'Skyscraper',
  'Tower',
  'Monument',
];

export const getStructureById = (id: string) =>
  structures.find(s => s.id === id);
