import { QuizQuestion } from '../models';

export const quizQuestions: QuizQuestion[] = [
  { id: 'q1', question: 'Which is the tallest building in the world?', options: ['Shanghai Tower', 'Burj Khalifa', 'Taipei 101', 'CN Tower'], correctIndex: 1 },
  { id: 'q2', question: 'In which city is the Eiffel Tower located?', options: ['Rome', 'Paris', 'Berlin', 'Madrid'], correctIndex: 1 },
  { id: 'q3', question: 'What is the primary function of Tokyo Skytree?', options: ['Hotel', 'Broadcasting tower', 'Office building', 'Museum'], correctIndex: 1 },
  { id: 'q4', question: 'Which skyscraper is located in New York?', options: ['Lotte World Tower', 'One World Trade Center', 'Shanghai Tower', 'Burj Khalifa'], correctIndex: 1 },
  { id: 'q5', question: 'Which country is home to the CN Tower?', options: ['USA', 'Canada', 'UK', 'Australia'], correctIndex: 1 },
  { id: 'q6', question: 'What material made skyscrapers possible?', options: ['Wood', 'Steel', 'Glass', 'Brick'], correctIndex: 1 },
  { id: 'q7', question: 'Which tower is known for its twisting design?', options: ['CN Tower', 'Shanghai Tower', 'Eiffel Tower', 'KL Tower'], correctIndex: 1 },
  { id: 'q8', question: 'What is the height of Burj Khalifa approximately?', options: ['500 m', '828 m', '700 m', '900 m'], correctIndex: 1 },
  { id: 'q9', question: 'Which structure is a monument?', options: ['Taipei 101', 'Eiffel Tower', 'Ping An Tower', 'Shanghai Tower'], correctIndex: 1 },
  { id: 'q10', question: 'What city is Taipei 101 located in?', options: ['Tokyo', 'Taipei', 'Seoul', 'Beijing'], correctIndex: 1 },
  { id: 'q11', question: 'What is the main purpose of observation towers?', options: ['Living space', 'Viewing city landscapes', 'Storage', 'Farming'], correctIndex: 1 },
  { id: 'q12', question: 'Which tower is in Kuala Lumpur?', options: ['CN Tower', 'KL Tower', 'Sky Tower', 'Tokyo Tower'], correctIndex: 1 },
  { id: 'q13', question: 'Which building has a tuned mass damper?', options: ['CN Tower', 'Taipei 101', 'Eiffel Tower', 'Burj Khalifa'], correctIndex: 1 },
  { id: 'q14', question: 'What does the Gateway Arch represent?', options: ['Freedom', 'Expansion westward', 'Technology', 'Trade'], correctIndex: 1 },
  { id: 'q15', question: 'Which city is known for the Oriental Pearl Tower?', options: ['Beijing', 'Shanghai', 'Hong Kong', 'Seoul'], correctIndex: 1 },
  { id: 'q16', question: 'What is inside many skyscrapers?', options: ['Farms', 'Shopping malls', 'Forests', 'Lakes'], correctIndex: 1 },
  { id: 'q17', question: 'Which structure was once the tallest in the world?', options: ['Eiffel Tower', 'CN Tower', 'Burj Khalifa', 'Tokyo Skytree'], correctIndex: 0 },
  { id: 'q18', question: 'Which country is Burj Khalifa in?', options: ['Qatar', 'UAE', 'Saudi Arabia', 'Kuwait'], correctIndex: 1 },
  { id: 'q19', question: 'What is a key feature of CN Tower?', options: ['Sky garden', 'Glass floor', 'Museum', 'Bridge'], correctIndex: 1 },
  { id: 'q20', question: 'Which tower is in Auckland?', options: ['Sky Tower', 'CN Tower', 'KL Tower', 'Canton Tower'], correctIndex: 0 },
  { id: 'q21', question: 'What helps skyscrapers resist wind?', options: ['Wood', 'Shape design', 'Paint', 'Color'], correctIndex: 1 },
  { id: 'q22', question: 'Which tower lights up at night?', options: ['Many towers', 'Only one', 'None', 'Only old towers'], correctIndex: 0 },
  { id: 'q23', question: 'What is a common skyscraper material?', options: ['Clay', 'Glass', 'Sand', 'Plastic'], correctIndex: 1 },
  { id: 'q24', question: 'Which monument is in Brazil?', options: ['Eiffel Tower', 'Christ the Redeemer', 'Gateway Arch', 'CN Tower'], correctIndex: 1 },
  { id: 'q25', question: 'What is the purpose of deep foundations?', options: ['Decoration', 'Stability', 'Color', 'Light'], correctIndex: 1 },
  { id: 'q26', question: 'Which structure is in Moscow?', options: ['CN Tower', 'Ostankino Tower', 'Sky Tower', 'KL Tower'], correctIndex: 1 },
  { id: 'q27', question: 'What type of structure is Statue of Liberty?', options: ['Skyscraper', 'Tower', 'Monument', 'Bridge'], correctIndex: 2 },
  { id: 'q28', question: 'What is the main use of broadcast towers?', options: ['Living', 'Communication signals', 'Storage', 'Transport'], correctIndex: 1 },
  { id: 'q29', question: 'Which structure is in Seoul?', options: ['Taipei 101', 'Lotte World Tower', 'CN Tower', 'Sky Tower'], correctIndex: 1 },
  { id: 'q30', question: 'Which country has Sydney Tower?', options: ['UK', 'USA', 'Australia', 'Canada'], correctIndex: 2 },
  { id: 'q31', question: 'What is a skywalk?', options: ['Bridge', 'Extreme tower attraction', 'Elevator', 'Window'], correctIndex: 1 },
  { id: 'q32', question: 'Which tower is in Tehran?', options: ['Milad Tower', 'CN Tower', 'KL Tower', 'Sky Tower'], correctIndex: 0 },
  { id: 'q33', question: 'Which structure is tallest tower?', options: ['CN Tower', 'Tokyo Skytree', 'Eiffel Tower', 'KL Tower'], correctIndex: 1 },
  { id: 'q34', question: 'What does LED lighting do on towers?', options: ['Heating', 'Decoration', 'Cooling', 'Strength'], correctIndex: 1 },
  { id: 'q35', question: 'Which monument is in Lisbon?', options: ['Gateway Arch', 'Monument to Discoveries', 'Eiffel Tower', 'CN Tower'], correctIndex: 1 },
  { id: 'q36', question: 'Which building is in Beijing?', options: ['CITIC Tower', 'CN Tower', 'Eiffel Tower', 'Sky Tower'], correctIndex: 0 },
  { id: 'q37', question: 'What is a key purpose of monuments?', options: ['Living', 'Honoring history', 'Storage', 'Travel'], correctIndex: 1 },
  { id: 'q38', question: 'Which tower is known for spheres design?', options: ['Tokyo Tower', 'Oriental Pearl Tower', 'CN Tower', 'KL Tower'], correctIndex: 1 },
  { id: 'q39', question: 'What affects tower visibility?', options: ['Music', 'Weather', 'Color', 'Height only'], correctIndex: 1 },
  { id: 'q40', question: 'What is golden hour best for?', options: ['Sleeping', 'Photography', 'Eating', 'Driving'], correctIndex: 1 },
  { id: 'q41', question: 'What is the tallest arch in the world?', options: ['Eiffel Tower', 'Gateway Arch', 'CN Tower', 'Burj Khalifa'], correctIndex: 1 },
  { id: 'q42', question: 'What do many towers symbolize?', options: ['Food', 'City identity', 'Music', 'Water'], correctIndex: 1 },
  { id: 'q43', question: 'Which structure is in Toronto?', options: ['CN Tower', 'KL Tower', 'Sky Tower', 'Eiffel Tower'], correctIndex: 0 },
  { id: 'q44', question: 'What can you find at the top of towers?', options: ['Forest', 'Observation deck', 'Farm', 'River'], correctIndex: 1 },
  { id: 'q45', question: 'Which tower is in China?', options: ['Canton Tower', 'CN Tower', 'Sky Tower', 'Sydney Tower'], correctIndex: 0 },
  { id: 'q46', question: 'Why are skyscrapers tall?', options: ['Decoration', 'Save space in cities', 'Fun', 'Tradition'], correctIndex: 1 },
  { id: 'q47', question: 'Which monument is in Kyiv?', options: ['Eiffel Tower', 'Motherland Monument', 'CN Tower', 'Gateway Arch'], correctIndex: 1 },
  { id: 'q48', question: 'What do towers often have at the top?', options: ['Pools', 'Antennas', 'Gardens only', 'Roads'], correctIndex: 1 },
  { id: 'q49', question: 'Which structure is in Mexico City?', options: ['Monumento a la Revolución', 'Eiffel Tower', 'CN Tower', 'Sky Tower'], correctIndex: 0 },
  { id: 'q50', question: 'What makes skyscrapers modern?', options: ['Wood', 'Technology and design', 'Size only', 'Color'], correctIndex: 1 },
];

export const pickRandomQuiz = (count: number): QuizQuestion[] => {
  const shuffled = [...quizQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};
