import { FactItem } from '../models';

export const facts: FactItem[] = [
  { id: 's1', category: 'Skyscraper', topic: 'Records', text: 'Burj Khalifa can be seen from over 90 km away.' },
  { id: 's2', category: 'Skyscraper', topic: 'Technology', text: 'Many skyscrapers are designed to slightly sway in the wind.' },
  { id: 's3', category: 'Skyscraper', topic: 'Technology', text: 'Taipei 101 uses a giant tuned mass damper to reduce movement.' },
  { id: 's4', category: 'Skyscraper', topic: 'Design', text: 'Modern skyscrapers often use double-skin facades for energy efficiency.' },
  { id: 's5', category: 'Skyscraper', topic: 'Technology', text: 'The fastest elevators in the world are found in supertall buildings.' },
  { id: 's6', category: 'Skyscraper', topic: 'History', text: 'Skyscrapers changed city skylines dramatically in the 20th century.' },
  { id: 's7', category: 'Skyscraper', topic: 'Construction', text: 'Steel-frame construction made skyscrapers possible.' },
  { id: 's8', category: 'Skyscraper', topic: 'Design', text: 'Some skyscrapers have entire shopping malls inside.' },
  { id: 's9', category: 'Skyscraper', topic: 'Construction', text: 'Wind tunnels are used to test skyscraper designs before construction.' },
  { id: 's10', category: 'Skyscraper', topic: 'Design', text: 'Glass is one of the most common materials in modern skyscrapers.' },
  { id: 's11', category: 'Skyscraper', topic: 'Construction', text: 'The Empire State Building was completed in just over a year.' },
  { id: 's12', category: 'Skyscraper', topic: 'Technology', text: 'Many skyscrapers include green technologies like solar panels.' },
  { id: 's13', category: 'Skyscraper', topic: 'Construction', text: 'Skyscrapers often use special foundations to support massive weight.' },
  { id: 's14', category: 'Skyscraper', topic: 'Design', text: 'Some buildings have sky gardens to improve air quality.' },
  { id: 's15', category: 'Skyscraper', topic: 'Technology', text: 'Elevators in skyscrapers can travel over 60 km/h.' },
  { id: 's16', category: 'Skyscraper', topic: 'History', text: 'The term "skyscraper" first appeared in the late 1800s.' },
  { id: 's17', category: 'Skyscraper', topic: 'Design', text: 'Some skyscrapers are inspired by natural shapes like mountains or waves.' },
  { id: 's18', category: 'Skyscraper', topic: 'Technology', text: 'Tall buildings can slightly influence local wind patterns.' },
  { id: 's19', category: 'Skyscraper', topic: 'Construction', text: 'Construction of supertall towers can take several years to complete.' },
  { id: 's20', category: 'Skyscraper', topic: 'Records', text: 'Most of the world\u2019s tallest skyscrapers are located in Asia.' },

  { id: 'm1', category: 'Monument', topic: 'History', text: 'The Eiffel Tower was originally intended to be temporary.' },
  { id: 'm2', category: 'Monument', topic: 'History', text: 'Many monuments are built to honor historical events or figures.' },
  { id: 'm3', category: 'Monument', topic: 'History', text: 'The Statue of Liberty was a gift from France to the United States.' },
  { id: 'm4', category: 'Monument', topic: 'Design', text: 'Some monuments are designed in the shape of obelisks.' },
  { id: 'm5', category: 'Monument', topic: 'Records', text: 'Monuments often become national symbols.' },
  { id: 'm6', category: 'Monument', topic: 'Records', text: 'The Gateway Arch is the tallest arch in the world.' },
  { id: 'm7', category: 'Monument', topic: 'Construction', text: 'Many monuments are constructed using stone or reinforced concrete.' },
  { id: 'm8', category: 'Monument', topic: 'Construction', text: 'Some monuments take decades to complete.' },
  { id: 'm9', category: 'Monument', topic: 'Design', text: 'Certain monuments include museums or viewing areas inside.' },
  { id: 'm10', category: 'Monument', topic: 'History', text: 'Monuments reflect cultural identity and heritage.' },
  { id: 'm11', category: 'Monument', topic: 'Records', text: 'The Eiffel Tower was once the tallest man-made structure.' },
  { id: 'm12', category: 'Monument', topic: 'Records', text: 'Some monuments can be seen from miles away.' },
  { id: 'm13', category: 'Monument', topic: 'Design', text: 'Monuments are often placed in central or symbolic locations.' },
  { id: 'm14', category: 'Monument', topic: 'History', text: 'Many monuments are protected as historical landmarks.' },
  { id: 'm15', category: 'Monument', topic: 'Construction', text: 'Construction techniques for monuments have evolved over centuries.' },
  { id: 'm16', category: 'Monument', topic: 'History', text: 'Some monuments commemorate wars or important victories.' },
  { id: 'm17', category: 'Monument', topic: 'Design', text: 'Visitors can climb or access observation areas in some monuments.' },
  { id: 'm18', category: 'Monument', topic: 'Design', text: 'Many monuments are beautifully illuminated at night.' },
  { id: 'm19', category: 'Monument', topic: 'Records', text: 'Monuments attract millions of tourists every year.' },
  { id: 'm20', category: 'Monument', topic: 'History', text: 'Some monuments were controversial at the time of construction.' },

  { id: 't1', category: 'Tower', topic: 'Records', text: 'Tokyo Skytree is the tallest tower in the world.' },
  { id: 't2', category: 'Tower', topic: 'Technology', text: 'Many towers are used for broadcasting television and radio signals.' },
  { id: 't3', category: 'Tower', topic: 'Design', text: 'Observation towers are designed to provide panoramic city views.' },
  { id: 't4', category: 'Tower', topic: 'Design', text: 'Some towers change colors at night using LED lighting systems.' },
  { id: 't5', category: 'Tower', topic: 'History', text: 'CN Tower was once the tallest free-standing structure in the world.' },
  { id: 't6', category: 'Tower', topic: 'Construction', text: 'Towers usually require less floor space compared to skyscrapers.' },
  { id: 't7', category: 'Tower', topic: 'Design', text: 'Some towers include rotating restaurants at the top.' },
  { id: 't8', category: 'Tower', topic: 'Technology', text: 'Broadcasting towers must be extremely stable to function properly.' },
  { id: 't9', category: 'Tower', topic: 'Records', text: 'Many towers are among the most visited tourist attractions.' },
  { id: 't10', category: 'Tower', topic: 'Construction', text: 'Towers are often built on elevated terrain to improve signal reach.' },
  { id: 't11', category: 'Tower', topic: 'Design', text: 'Their curved shapes help reduce wind resistance.' },
  { id: 't12', category: 'Tower', topic: 'Technology', text: 'Towers can serve both technical and entertainment purposes.' },
  { id: 't13', category: 'Tower', topic: 'History', text: 'Some towers are illuminated to celebrate holidays and events.' },
  { id: 't14', category: 'Tower', topic: 'History', text: 'Early towers were used as watchtowers for defense.' },
  { id: 't15', category: 'Tower', topic: 'Design', text: 'Modern towers often feature glass observation decks.' },
  { id: 't16', category: 'Tower', topic: 'Records', text: 'Towers often become defining symbols of their cities.' },
  { id: 't17', category: 'Tower', topic: 'Technology', text: 'Some towers offer extreme attractions like skywalks or bungee jumps.' },
  { id: 't18', category: 'Tower', topic: 'Construction', text: 'Deep foundations are essential for tall tower stability.' },
  { id: 't19', category: 'Tower', topic: 'Technology', text: 'Towers play a key role in global communication networks.' },
  { id: 't20', category: 'Tower', topic: 'Construction', text: 'Lightweight materials are often used in modern tower construction.' },
];
